module.exports = {
  SLUG_TAKEN: 'SL02',
  ACCESS_CODE_REQUIRED_PRIVATE: 'AC01',
  ACCESS_CODE_NOT_ALLOWED_PUBLIC: 'AC05',
  CARD_NOT_FOUND: 'NF01',
  CARD_IS_DRAFT: 'NF02',
  PRIVATE_CARD_ACCESS_REQUIRED: 'AC03',
  INVALID_ACCESS_CODE: 'AC04',
  CREATOR_REFERENCE_MISMATCH: 'CR01',
};
